FROM php:7.3.18-apache

# modrewirte
RUN a2enmod rewrite

# copy default index.php for testing. getting overwritten from a volume later...
COPY ./assets/index.php /var/www/html/index.php

# configure apache
COPY ./assets/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY ./assets/ErrorDocument.php /var/www/html_errordocument/ErrorDocument.php

# overwrite docker entrypoint
COPY ./docker-cmd.sh /docker-cmd.sh
RUN chmod +x /docker-cmd.sh
CMD /docker-cmd.sh