FROM base

# install some packages
RUN apt-get update && apt-get install -y \
    # python
    python2 python-pip python-dev build-essential \
    # cleanup
    && rm -r /var/lib/apt/lists/*

# install python modules
RUN pip2 install js2py pytz tzlocal cfscrape