#!/bin/bash

# exit when any command fails
set -e
trap "exit \$?" INT TERM EXIT

source hooks/tags

if [ "${SOURCE_BRANCH}" = "beta" ]; then
    echo "Beta-Branche. Images will be tagged with -beta."
    suffix="-beta"
else
    suffix=""
fi

for tag in "${TAGS[@]}"; do
    echo "Pushing ${DOCKER_REPO}:${tag}${suffix}..."
    docker push ${DOCKER_REPO}:${tag}${suffix}
done